### ISSUE TITLE
Login form does not work with -host 0.0.0.0

### ISSUE THREAD

**Issue by emetsger** [CenterForOpenScience/fakecas#6]
Currently the `-host` command line parameter controls the binding of the fakecas server to a IP address and port.  It is also used when static HTML is rendered; the `action` of the login form uses the value of the `-host` parameter.

When the value of the `-host` command line parameter is the wildcard address (`0.0.0.0:8080`), the login form is also rendered with an action of `http://0.0.0.0:8080/`.  Obviously, form submissions to 0.0.0.0 won't work.  

If `-host` is an unreliable way of obtaining the public IP address of the CAS login server, an alternative mechanism needs to be implemented.  Possibilities include:
- Deducing the public IP address/name from the HTTP `host` header
- Adding an additional command line parameter to specify the host
- Others

**Comment by emetsger** [comment]
Another mechanism suggested by @chrisseto is to simply use a relative URL in the login form, eliminating the need to parse `Host` headers or adding any additional command line options.

**Comment by cslzchen** [comment]
Looks to me the issue has been solved with https://github.com/CenterForOpenScience/fakecas/pull/8. Issue closed.
